### ISSUE TITLE
import CORE_DIRECTIVES's missing

### ISSUE THREAD

**Issue by yahyaKacem** [Stabzs/Angular2-Toaster#38] opened 2016-06-23 16:46 UTC
Missing import { Core_Directives } from '@angular/common'; [line 44](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toast.component.ts#L44)

```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngSwitchCase' since it isn't a known native property ("ngClass]="toast.toasterConfig.messageClass" [ngSwitch]="toast.bodyOutputType">
                <div [ERROR ->]*ngSwitchCase="bodyOutputType.Component" #componentBody></div>
                <div *ngSwitchCase="bo"): ToastComponent@5:21
Property binding ngSwitchCase not used by any directive on an embedded template ("div [ngClass]="toast.toasterConfig.messageClass" [ngSwitch]="toast.bodyOutputType">
                [ERROR ->]<div *ngSwitchCase="bodyOutputType.Component" #componentBody></div>
                <div *ngSwitchCas"): ToastComponent@5:16
Can't bind to 'ngSwitchCase' since it isn't a known native property ("           <div *ngSwitchCase="bodyOutputType.Component" #componentBody></div>
                <div [ERROR ->]*ngSwitchCase="bodyOutputType.TrustedHtml" [innerHTML]="toast.body"></div>
                <div *ngSw"): ToastComponent@6:21
Property binding ngSwitchCase not used by any directive on an embedded template ("                <div *ngSwitchCase="bodyOutputType.Component" #componentBody></div>
                [ERROR ->]<div *ngSwitchCase="bodyOutputType.TrustedHtml" [innerHTML]="toast.body"></div>
                <div "): ToastComponent@6:16
Can't bind to 'ngSwitchCase' since it isn't a known native property ("div *ngSwitchCase="bodyOutputType.TrustedHtml" [innerHTML]="toast.body"></div>
                <div [ERROR ->]*ngSwitchCase="bodyOutputType.Default">{{toast.body}}</div>
            </div>
        </div>
"): ToastComponent@7:21
Property binding ngSwitchCase not used by any directive on an embedded template ("    <div *ngSwitchCase="bodyOutputType.TrustedHtml" [innerHTML]="toast.body"></div>
                [ERROR ->]<div *ngSwitchCase="bodyOutputType.Default">{{toast.body}}</div>
            </div>
        </div>
"): ToastComponent@7:16
```

**Comment by Stabzs** [comment] 2016-06-23 16:50
Most likely a duplicate of https://github.com/Stabzs/Angular2-Toaster/issues/34

**Closed** 2016-06-24 15:31 UTC
Labels: duplicate, question
