### ISSUE TITLE
parameters with custom component

### ISSUE THREAD

**Issue by deniskkk** [Stabzs/Angular2-Toaster#124] opened 2017-07-31 09:03 UTC
Is there a way to pass parameters to custom component? for example "message" to show on toaster creation

**Comment by Stabzs** [comment] 2017-07-31 21:50
It isn't clear exactly what you are trying to accomplish, but this should be a duplicate of https://github.com/Stabzs/Angular2-Toaster/issues/112.  Please let me know if for whatever reason it doesn't solve your needs.

**Closed by Stabzs** 2017-07-31 21:50 UTC
