### ISSUE TITLE
AoT 1.1.0 Unexpected value 'ToasterModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by philjones88** [Stabzs/Angular2-Toaster#89] opened 2016-12-20 12:18 UTC
Looks to be the same as #55 

I'm using:

TS 2.0.10
NG 2.3.1
Angular2-toaster 1.1.0

```
$ rm -rf aot && yarn run ngc
yarn run v0.17.10
$ ngc -p tsconfig.aot.json
Error: Unexpected value 'ToasterModule' imported by the module 'AppModule'
    at /Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:17768:46
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:17753:51)
    at addNgModule (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:24349:60)
    at /Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:24360:16
    at Array.forEach (native)
    at _createNgModules (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:24359:28)
    at analyzeNgModules (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:24238:16)
    at analyzeAndValidateNgModules (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:24248:37)
    at AotCompiler.compileAll (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:23987:20)
Compilation failed
error Command failed with exit code 1.
```

Mostly following the official AoT cookbook at https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by cedricduffournet** [comment] 2016-12-20 14:26
An issue has already see: #87

> Linking directly to angular2-toaster/lib/toaster.module allows the application to be consumed by AoT.

**Comment by Stabzs** [comment] 2016-12-20 18:37
@philjones88 this is a duplicate of #87 .  A permanent fix is being worked on and in the meantime, you can use the workaround noted in that issue as cedric called out.

**Closed by Stabzs** 2016-12-20 18:37 UTC
