### ISSUE TITLE
ClickHandler is called twice on exit button press

### ISSUE THREAD

**Issue by gurdilou** [Stabzs/Angular2-Toaster#35] opened 2016-06-21 13:47 UTC
Hi,

I try to handle toast clicks, so I attached a function to  the ClickHandler  :

```typescript
    let toast: Toast = {
        type: 'info',
        title: title,
        body: 'Click here to cancel',
        showCloseButton: true,
        timeout: 9000,

        clickHandler: (toast , isCloseButton) => {
          console.log("isCloseButton : "+isCloseButton);
          return true;
        }
    };
    this.toastr.pop(toast);
```

But the function is called twice when the user press the exit button.

Have I missed something ?

**Comment by Stabzs** [comment] 2016-06-21 23:01
The above sample looks reasonable.

Could you please create a plunker that demonstrates the behavior?  I can't reproduce it.

**Comment by gurdilou** [comment] 2016-06-22 08:28
Sure.

http://plnkr.co/edit/BhaQ6VypGntO83FHXVOV?p=preview

**Comment by Stabzs** [comment] 2016-07-08 02:31
Apologies for the delayed fix. This was a bug only when the ClickHandler evaluated to false and the toast was not removed.  

This will be included in the next release.

**Closed** 2016-07-08 02:31 UTC
Labels: bug
