### ISSUE TITLE
can't use that module with angular-cli optimized builds

### ISSUE THREAD

**Issue by ToGoBananas** [Stabzs/Angular2-Toaster#128] opened 2017-09-14 15:07 UTC
Hi
I am using angular/cli=1.4.2, typescript=2.5.2 and latest version of Angular2-Toaster
I am trying to compile my app like `ng build -e=prod -aot --build-optimizer`, but I have these errors: 
![image](https://user-images.githubusercontent.com/5418148/30437418-3d028c1c-9977-11e7-99bd-3854db3d8ff5.png)
my component
![image](https://user-images.githubusercontent.com/5418148/30437470-6019c24c-9977-11e7-8443-f017f2abae60.png)
problematic line in toaster.js
![image](https://user-images.githubusercontent.com/5418148/30437520-8086ad24-9977-11e7-9225-44bb098f27a4.png)

**Comment by ToGoBananas** [comment] 2017-09-14 15:10
It looks like easy issues tp fix, but I just wodering why `BodyOutputType.Default` expression fails

**Comment by ToGoBananas** [comment] 2017-09-14 15:13
I think I just need to override configs, but maybe you want to fix that issue

**Comment by Stabzs** [comment] 2017-09-15 00:28
This is very curious...the BodyOutputType IS defaulted intentionally. I suspect this is due to the optimize flag attempting dead code elimination and it may believe the property isn't needed. I will try to reproduce.

**Comment by Stabzs** [comment] 2018-02-23 05:09
This is currently fixed in 5.0.0-beta.1 and will be released in the full 5.0.0 release.

**Comment by Stabzs** [comment] 2018-02-24 16:11
Released in 5.0.0.

**Closed by Stabzs** 2018-02-24 16:11 UTC
