### ISSUE TITLE
how to define container once , not in every component

### ISSUE THREAD

**Issue by GHR-Arash** [Stabzs/Angular2-Toaster#129] opened 2017-09-18 12:03 UTC
I would not like to define a container in every component I intend to pop a toaster, I would like to define it once in root component. where application bootstrap but when I do so, I get the error

 No Toaster Containers have been initialized to receive toasts.

**Comment by Stabzs** [comment] 2017-09-18 12:34
That is exactly how the library is intended to be used.  Are you declaring your container outside of your router?

It you create a plunker demonstrating the issue I'm happy to take a look.

**Comment by MassiveHiggsField** [comment] 2017-09-20 09:47
I dont know if my problem is the same as the original posters, but i've created a repo which produces the same error:

https://github.com/MassiveHiggsField/angular-toaster-test

Just checkout, "npm install" and "ng serve" to start it up. 

I think the problem is how i use routes and the user module, specifically this: 

https://github.com/MassiveHiggsField/angular-toaster-test/blob/1ecee76dfd8cf72ada4261aae9c488d987ee0192/src/app/routes/routes.module.ts#L12

**Comment by devakone** [comment] 2017-09-25 19:54
@MassiveHiggsField  I use lazily loaded modules and I also run into the same issue.

**Comment by Stabzs** [comment] 2017-09-26 03:24
All, sorry for the delayed response on this thread.

@MassiveHiggsField thanks for the helpful reproduction.

Due to ToasterService being bundled as a provider within the ToasterModule, it is instantiated when loaded.  It seems that loading the container apart from the service is causing the original subscriptions to get replaced and not bound to the correct container instance.  Moving the ToasterModule inclusion from shared to Layout (where the actual `<toaster-container></toaster-container>` lives) fixes this problem.  Alternatively, foregoing the NgModule inclusion and directly importing the container per component might also resolve the problem.

However, all of these options are probably short-lived solutions.  I'm looking into a better way to persist subscriptions per instantiation or otherwise ensure that the subscription is always valid.

**Comment by devakone** [comment] 2017-09-26 14:55
@Stabzs shouldn't the ToasterModule by default be offered with a `forRoot` method to ensure that the ToasterService is primarily served as a singleton?

**Comment by Stabzs** [comment] 2017-09-26 16:18
@devakone I'm looking into that as an option although there are concerns with `forRoot` being called from a shared module due to memory leaks.

When exposing a `forRoot` implementation, my understanding is that it should literally only be called in the application root, which isn't the pattern that @MassiveHiggsField is using with a shared module.

It might be necessary to expose both a `forRoot` and a `forChild` implementation...one for the actual root when bootstrapping the library in your root module and another for bootstrapping the library in any lower level modules and/or a shared module.  This may be the correct approach and I'm going to spend some additional time working through it to identify all of the scenarios and ensure that a change solves for all of them.

Adding either implementation is a breaking change requiring a major version, so the solution has to be correct the first time :).

**Comment by devakone** [comment] 2017-09-26 16:21
You hit it right on the head. I was going to suggest the `forRoot` providing the service and the container component and `forChild` only providing the container component, this way you can ensure that a singleton version of the service exist that can handle the proper hydration of the created components.

**Comment by MassiveHiggsField** [comment] 2017-09-26 16:22
First of all, thanks for the effort @Stabzs :+1: and @devakone for the additional input.

But since it requires a major version and these things normaly take time, do you have some advice for me for now?

**Comment by devakone** [comment] 2017-09-26 16:43
@MassiveHiggsField i would recommended keeping the course for now until the update which I don't think will take such a long time. In my case, I just redefine the container at the root component of my lazily loaded module and it works then for all components within that lazily loaded module. A small price to pay for now.

**Comment by Stabzs** [comment] 2017-09-26 16:48
@MassiveHiggsField @devakone I would agree.  The easiest solution is to import the ToasterModule in layout (since that is where you are rendering the component).  That'll unblock you and when I tested it in your code, it worked just fine.

**Comment by MassiveHiggsField** [comment] 2017-09-27 07:48
Alright, thanks for the suggestions :)

**Comment by Stabzs** [comment] 2018-02-23 05:08
This is currently added in 5.0.0-beta.1 and will be released in the full 5.0.0 release.

**Comment by Stabzs** [comment] 2018-02-24 16:11
Released in 5.0.0.

**Closed by Stabzs** 2018-02-24 16:11 UTC
Labels: enhancement, question
