### ISSUE TITLE
IE11 "right" positionClass is ignored when more than one toaster is on the screen

### ISSUE THREAD

**Issue by draiche** [Stabzs/Angular2-Toaster#102] opened 2017-02-27 05:44 UTC
I was trying to create a plunker for this bug, but IE won't even load any plunker demos of this library for some reason. In IE11 I've found that when using a positionClass of "toast-top-right" or "toast-bottom-right", the toasts are only positioned correctly for the first toast that appears. After a second one appears on the screen while the first one is also still displayed, the toasts ignore the "right: 12px" CSS and jump over to the left side of the browser. If you hover over the toasts, they jump back to the right side of the screen until a new toast is added, at which point they jump back to the left side.

 In my testing it seems simply adding "width: 300px" to "#toast-container {", line 108 in toaster.css fixes the issue. The toasts are always set to 300px themselves in this case, so it doesn't appear any different, but for some reason IE seems to need the parent container to have a specified width. However, I'm not sure if this has any impact on the rest of the library. I haven't noticed any issues, but I only really use it for our specific use case.

The issue does not seem to appear when using any left or center positions.

**Comment by Stabzs** [comment] 2017-02-28 02:05
@draiche  thanks for the thorough and detailed information!

IE11 fails for the plunkers due to a missing SystemJS-dependency polyfill  I'll see if I can find a way to "unbreak" these plunkers in IE11 to make it easier to test and report issues in the future.

Thank you also for tested fix.  I'll regress this further and see if it can be applied safely.

**Comment by Stabzs** [comment] 2017-02-28 02:14
@draiche http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview has been updated with the core-js polyfill which solves the IE11/SystemJS plunker issues.

**Comment by draiche** [comment] 2017-02-28 02:26
Thanks for the update!

A quick test in the updated plunker isn't producing the issue for me, so I don't really know what to make of that. While I can't imagine what would be messing with it in our application, perhaps it's something on our end... Adding the 300px width as an override did fix it as I mentioned for our app, but if it's not reproduceable elsewhere then I'm not sure what to say.

Either way, at least we have working IE11 plunkers now, so hurray for that! This could be closed as non-reproduceable if you want. Your call.

**Comment by Stabzs** [comment] 2017-02-28 02:32
@draiche I've expanded the above plunker with an explicit configuration override to try to reproduce the issue without any luck:  http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview. 

In the meantime, I think it is reasonable to close this issue as non-reproduceable, but please update the issue if you discover anything else since I definitely want to prevent issues.

**Closed** 2017-02-28 02:42 UTC
Labels: reproduction needed
