### ISSUE TITLE
BodyOutputType.Component with template bindings not working

### ISSUE THREAD

**Issue by sprell** [Stabzs/Angular2-Toaster#71] opened 2016-10-12 01:54 UTC
Is there a working demo using BodyOutputType.Component with template bindings? Whenever I try to add bindings or interpolation to the template I get the following error.

Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: 'Some value loaded via component'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

I have a modified version of your plunker demonstrating this issue here...
http://plnkr.co/edit/d8xggIUEQxtwzNrANlZh

If you remove the "{{someValue}}" from the template, it will work fine. Any idea what might be wrong here? This used to work with versions prior to the official Angular2 release.

Thanks.

**Comment by Stabzs** [comment] 2016-10-12 03:35
Thanks for the modified plunker.

This looks like this is caused by changes made post rc.5 that do not allow new model changes in `ngAfterViewInit()`, which is the hook used for dynamic rendering since it is not until that point that the new `componentFactoryResolver` can render the component.

This should be as simple as forcing change detection within the lifecycle hook.  This was not properly covered by tests and as a result never showed up.

Thanks for bringing this up.  This will be fixed soon.

**Closed** 2016-10-12 22:24 UTC
Labels: bug
