### ISSUE TITLE
Upgrade to Angular 2.3.0 to satisfy peer Dependencies on next Minor version

### ISSUE THREAD

**Issue by alyahmedaly** [Stabzs/Angular2-Toaster#87] opened 2016-12-10 03:23 UTC
npm WARN angular2-toaster@1.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was
installed.
UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4

**Comment by Stabzs** [comment] 2016-12-11 01:15
That is nothing more than an npm warning, not an error.

You can absolutely use `angular2-toaster@1.1.0` with `@angular@2.3.0` and `rxjs@5.0.0-rc.4` as shown in this [plunker](http://plnkr.co/edit/uUgo1ybhotw8QJX4elTo?p=preview).

This is simply a warning and will not prevent you from using the library.  Since the goal of previous versions of angular2-toaster was to try to be more accommodating of the angular 2 release cycles, these are simply peer dependencies that you must fulfill, not dependencies.  As such, while it will warn you, it shouldn't actually prevent you from resolving any of the packages.

This will be updated to a greater minimum rxjs version in the next minor release of angular2-toaster.

**Comment by scottmun** [comment] 2016-12-14 20:37
What about upgrading the angular version for AOT?

I'm getting the following error in the rollup phase:

'ToasterModule' is not exported by node_modules\angular2-toaster\angular2-toaste
r.js (imported by compiled-aot\src\app\common\app.module.js). For help fixing th
is error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-e
xported-by-module
Error: 'ToasterModule' is not exported by node_modules\angular2-toaster\angular2
-toaster.js (imported by compiled-aot\src\app\common\app.module.js). For help fi
xing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-i
s-not-exported-by-module

**Comment by Stabzs** [comment] 2016-12-15 21:05
@scottmun could you please provide additional details to reproduce?  Thanks

**Comment by scottmun** [comment] 2016-12-16 15:06
I'm importing the ToasterModule just like you laid out in your README. Works fine using JIT. Other 3rd party modules compiled with angular 2.2+ work fine.

**Comment by Stabzs** [comment] 2016-12-18 00:30
@scottmun what version of angular2-toaster are you using?  I could not reproduce any such issue via angular-cli running @angular@2.3.1 with the --prod and --aot flags.

**Comment by tomalex0** [comment] 2016-12-18 16:46
When  i upgraded to `angular 2.3.1`  i'm seeing 
`npm WARN angular2-toaster@1.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.`

This is preventing yo generate `npm shrinkwrap`

**Comment by cedricduffournet** [comment] 2016-12-18 20:05
I also encounter an issue with angular@2.3.1 and AOT. I get the error: 

```
Error: Unexpected value 'ToasterModule' imported by the module 'AppModule'
    at /opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:17768:46
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:17753:51)
    at addNgModule (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24349:60)
    at /opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24360:16
    at Array.forEach (native)
    at _createNgModules (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24359:28)
    at analyzeNgModules (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24238:16)
    at analyzeAndValidateNgModules (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:24248:37)
    at AotCompiler.compileAll (/opt/local/www/ngx-test/node_modules/@angular/compiler/bundles/compiler.umd.js:23987:20)
Compilation failed
```

I did a quick repo with my configuration https://github.com/dakodapp/ngx-test

Hope it helps

**Comment by Stabzs** [comment] 2016-12-19 04:11
@cedricduffournet Thank you so much for the very detailed repo.  It is extremely helpful.

There seems to be two different issues at play at the moment.  The warning in regards to rxjs is because the package version is fixed (since Angular 2 fixed versions) and was never updated to allow for minimum-required versions, which needs to change.  With the exception of @tomalex0 's issue around `npm-shrinkwrap`, this should be a temporary annoyance, not a blocker.

The issue present in your repo, as well as the issue reported by @scottmun seems to be something completely different.  Typically, this issue is caused by missing `.metadata.json` files, however, the files are generated, included, and present in your repo.

While currently the metadate files included in `angular2-toaster` are targeting version 1, when working with your repo and generating new version 3 AoT metadata.json files against `@angular/compiler-cli@2.3.1`, the issue is still present. 

I am currently looking through all changes from `@angular@2.0.0` to present day to try to understand what changed to break AoT compilation, especially when new metadata.json files do not seem to satisfy the AoT compiler.  

I'll continue to troubleshoot this and any suggestions or input is more than welcome.  I think that the rxjs warning is merely a red herring and that there is a larger issue with AoT compilation consumption of the library.

**Comment by Stabzs** [comment] 2016-12-19 04:32
It looks like the actual culprit here is the es5 compatible entrance point to the library at angular2-toaster.js.  Linking directly to `angular2-toaster/lib/toaster.module` allows the application to be consumed by AoT.

**Comment by cedricduffournet** [comment] 2016-12-19 12:09
Thanks for you help. I confirm that you solution fix my error.

**Comment by tomalex0** [comment] 2016-12-20 04:55
@Stabzs 
As of now i moved `angular2-toaster` out of `package.json` and  installing it from `posintsall` in `package.json`

**Comment by Stabzs** [comment] 2016-12-20 18:36
@cedricduffournet thank you for confirming!  This will be fixed shortly in the next release.

**Comment by Stabzs** [comment] 2016-12-20 18:37
@tomalex0 thanks for noting a workaround.  The rxjs requirement will be changed to `^5.0.0-beta.11` in the next release which should resolve your issue.

**Comment by cedricduffournet** [comment] 2016-12-20 18:47
@Stabzs I just a did a fix for this issue, I used Universal Module Definition compilation, webpack for test... I didn't made a PR because I'm not sure if you would like to go this way. Anyway you can check what I have done here : https://github.com/dakodapp/Angular2-Toaster/tree/umd_webpack
Maybe you can find some interesting stuff for next version

**Comment by Stabzs** [comment] 2016-12-20 18:55
@cedricduffournet thanks so much for the repo.  I was already considering moving to UMD since the angular 2 team adopted it and the current structure of the `angular2-toaster` repo is fragile, particularly in light of how the library needs to be consumed.  I appreciate your time putting the repo together.

**Comment by cedricduffournet** [comment] 2016-12-20 19:07
You are really welcome. 
Yes I think I could be great to move to UMD. The repo I made work well, it took me little time to adapt your existing project, I think it can help you.

**Comment by Stabzs** [comment] 2016-12-20 19:17
@cedricduffournet it looks great so far.  There's a lot of power using webpack and I had already been wanting to move to it for building the library since it handles so much of the grunt work.

One pain point will still be maintaining `@angular` dependencies as peer dependencies, so that consumers of the library can use any `@angular` version of `2.0.0` or greater, preventing forced updates unless new breaking changes come.  I'll have to see how well that plays out.

**Comment by alyahmedaly** [comment] 2016-12-20 21:34
Angular 2.4 released with rxjs ^5.0.1 ✌

**Comment by Stabzs** [comment] 2016-12-21 19:54
@cedricduffournet in your AoT work, did you notice badly formed metadata.json files reporting `{"__symbolic":"error","message":"Reference to a local symbol"` style errors?  I have a UMD branch complete but without properly formed metadata.json files, it can't be merged and released.

**Comment by Stabzs** [comment] 2016-12-21 21:58
@cedricduffournet the issue with metadata.json generation was caused by using a typescript version of 2.1.0 or greater.

**Comment by Stabzs** [comment] 2016-12-22 02:20
@alyahmedaly @scottmun @tomalex0 @cedricduffournet @GiuseppePiscopo Thank you all for your patience and input on these issues.

The library has been updated to UMD and published to NPM as `2.0.0` due to breaking changes in application structure, although the top-level APIs have in no way changed.  Please see details in the https://github.com/Stabzs/Angular2-Toaster/blob/master/CHANGELOG.md.

**Closed by Stabzs** 2016-12-22 02:20 UTC
Labels: bug, enhancement, question

**Comment by cedricduffournet** [comment] 2016-12-22 10:06
@Stabzs Thank you. It works great

**Comment by Stabzs** [comment] 2016-12-22 21:34
@cedricduffournet thank you for confirming!
