### ISSUE TITLE
Timeout does not seem to work

### ISSUE THREAD

**Issue by friksa** [Stabzs/Angular2-Toaster#25] opened 2016-06-04 09:57 UTC
Thanks for a great library!

The examples provided are clear and works great!  However, the timeout does not seem to work and the popups do not disappear after 5 seconds.  Even specifying a timeout does not work.

**Comment by Stabzs** [comment] 2016-06-04 14:02
What version are you using?  A timeout related bug was fixed in 0.3.2-rc.1. If you are using the latest version, please post a small, complete example that demonstrates the issue.

**Comment by friksa** [comment] 2016-06-04 14:10
I am using the npm version: 0.3.3-rc.1

My code is exactly the examples that you provide on github without any changes to.

**Comment by Stabzs** [comment] 2016-06-04 14:21
You'll have to be more specific.

If you abstain from providing any timeout parameter whatsoever, the default will be 5000ms and toasts will self-dismiss.  You can see an example of that here https://github.com/Stabzs/Angular2-Toaster/tree/master/demo/systemjs.  The second container `ToasterConfig` does not have a timeout property and any toasts in container 2 automatically dismiss after 5 seconds.

If that example still doesn't help clear things up, please provide a plunker that demonstrates the issue.  Thanks!

**Comment by friksa** [comment] 2016-06-04 14:57
That example does not have an issue with the timeout.  Even when I upgrade it to the latest version of your library it works good.  However, when I use your example code in our larger project, I have the issue with the timeout.  I will dig around more and let you know what I find, but for now I will close the issue.

**Comment by friksa** [comment] 2016-06-05 16:00
There is definitely an issue when everything is not defined in a single file as with your examples.  I am using an Angular seed project where things are more complicated.

These issues are related to zone.js

These changes to your ToasterContainerComponent fixes it for me:
````
import {NgZone, ChangeDetectorRef, Component, Input} from '@angular/core';

...

    constructor(toasterService: ToasterService,
                private zone: NgZone,
                private ref: ChangeDetectorRef) {

....


    private configureTimer(toast: Toast) {
        var timeout = (typeof toast.timeout === "number") 
            ? toast.timeout : this.toasterconfig.timeout;

        if (typeof timeout === "object") timeout = timeout[toast.type];
        if (timeout > 0) {
          var me = this;
          toast.timeoutId = window.setTimeout(() => {
            me.zone.run(() => {
              me.ref.markForCheck();  //make sure screen is updated
              me.removeToast(toast);
            });
          }, timeout);
        }
    }

````

**Comment by friksa** [comment] 2016-06-05 16:05
BTW, I see that popAsync has the issue... the toast is never displayed.

You can apply the same fix the the setTimeout used by popAsync.

**Comment by Stabzs** [comment] 2016-06-05 16:30
I disagree with the need for this change. If zones aren't working properly, that is systemic of your calling code, not the library. Monkey patching a forced zone call because of calling code not properly trigger zone change detection is certainly a code smell. 

How are you calling the toasts?  Are you calling them from within a socket provider running outside of a zone or on a non-patched call?

The fact that it works correctly in an isolated context but not in a larger context is the key determining factor.

**Comment by friksa** [comment] 2016-06-05 16:40
I buy that.  I am calling them on a mouse click right now.

I am using this seed project and there are many unknowns to me :)
https://github.com/NathanWalker/angular2-seed-advanced

I will have to learn more about the project and zone.js so I can report the issue to them.  Thanks for your advice!

**Comment by friksa** [comment] 2016-06-06 17:49
Turns out that the project ( https://github.com/NathanWalker/angular2-seed-advanced ) does not use default change detection strategy.  Instead it is using:
ChangeDetectionStrategy.OnPush;

Once I changed that to ChangeDetectionStrategy.Default, everything is working great.

**Comment by Stabzs** [comment] 2016-06-06 17:52
Ahh that explains it!  Great find!

**Comment by friksa** [comment] 2016-06-07 08:45
@Stabzs you may want to document that this project requires ChangeDetectionStrategy.Default.  There is definitely a push to use ChangeDetectionStrategy.OnPush for performance reasons in more complex/larger projects.

Alternatively, you could consider this a feature request to make this project work in all scenarios with this.ref.markForCheck();  I realize that the zone.run() is not needed though as per my original proposal.

**Comment by Stabzs** [comment] 2016-06-09 14:51
Great points.

After additional consideration, it seems that this is a reasonable scenario for explicitly marking for a change detection check.  It does not seem fair or reasonable to have the consumer take on this responsibility when the library can provide the functionality.

Also, considering that an explicit call to `zone.run()` is not required (I came to the same conclusion :)), this is no longer a behavioral issue caused by improper zone patching.

I"ll add this change in the near future.

**Closed** 2016-06-17 14:17 UTC
Labels: enhancement

**Comment by meakub1010** [comment] 2017-06-08 14:34
still not working.

**Comment by Stabzs** [comment] 2017-06-08 14:49
@meakub1010 "still not working" doesn't mean anything to me nor does it in any way help describe what issue you're seeing.  If you would be kind enough to create a plunker that clearly demonstrates what you are trying to do and in what way it is not working, i would be more than happy to take a look.

**Comment by meakub1010** [comment] 2017-06-08 15:21
@Stabzs I really liked your prompt response. I can't promise of replicating the issue in plnkr. But here is the brief. I was trying to use it in .net core project with AngularJS 4. Probably because of conflicts with other JS libraries we are using in that project timeout wasn't working as expected. 
After timeout span, toast used to loose focus. 
Hope that helps :)
Thanks
- Muhammad

**Comment by Stabzs** [comment] 2017-06-08 15:56
@meakub1010 this could be a variety of things including bad routing configuration in relation to the container or bad toasterconfig settings.  I can't give you too much assistance without seeing an example but if you're able to put one together, I'll take a look!
